# Generated by Django 2.1.7 on 2019-05-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190528_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='MaintenanceDate',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
