# Generated by Django 2.1.7 on 2019-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_maintenancelog_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='USN',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
