# Generated by Django 2.1.7 on 2019-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_partitem_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='PartItemId',
            field=models.IntegerField(default=73),
        ),
    ]
