# Generated by Django 2.1.7 on 2019-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190606_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemresult',
            name='Asset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
