# Generated by Django 2.1.7 on 2019-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190619_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemresult',
            name='Asset',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
