# Generated by Django 2.1.7 on 2019-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_partitem_creatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='USN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
