# Generated by Django 2.1.7 on 2019-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190621_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='Asset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partitem',
            name='NextCheckDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
