# Generated by Django 2.1.7 on 2019-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190621_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='OSN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
