# Generated by Django 2.1.7 on 2019-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190625_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='MaintainerId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partitem',
            name='CreatorId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
