# Generated by Django 2.1.7 on 2019-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190626_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemresult',
            name='ErrorCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partitemresult',
            name='FixtureId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partitemresult',
            name='OSN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partitemresult',
            name='Spec',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='partitemresult',
            name='Stage',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partitemresult',
            name='USN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
