# Generated by Django 2.1.7 on 2019-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20190705_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=50)),
                ('IsActivated', models.IntegerField(default=1)),
                ('UpdatedTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LocationLog',
            },
        ),
        migrations.AddField(
            model_name='partitem',
            name='LocationId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partitem',
            name='UseStatus',
            field=models.CharField(default='normal', max_length=30),
        ),
    ]
