# Generated by Django 2.1.7 on 2019-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20190816_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlog',
            name='IsActivated',
            field=models.BooleanField(default=True),
        ),
    ]
