# Generated by Django 2.1.7 on 2019-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20190816_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='TrnDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
