# Generated by Django 2.1.7 on 2019-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20190819_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='SubMaintainerIds',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partitem',
            name='SubMaintainers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partitem',
            name='WarningBeforeDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partitem',
            name='WarningBeforeTimes',
            field=models.IntegerField(null=True),
        ),
    ]
