"""
Django settings for AEMSLite project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '43+pjn1w6oo#1hex@ai@rf(bzy%qxhxf!#eikt!s&e15pjr2%r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.analysis',
    'app.maintain_monitor',
    'app.index',
    'app.login',
    'app.maintain',
    'app.NGrate',
    'app.management',
    'app.DBexcel',
    'django_crontab',    #定时任务
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AEMSLite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':["django.templatetags.static"],
        },
    },
]

WSGI_APPLICATION = 'AEMSLite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'aemslite',
        'USER': 'postgres',
        'PASSWORD': '1234qwer!@#$QWER',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CRONJOBS = [
    ('* */1 * * *','app.DBexcel.views.insert_many_to_partItemResult','>> /var/run.log'),
    ('* */1 * * *','app.DBexcel.views.update_for_partItem','>> /var/run.log'),
    ('0 4 * * *', 'app.DBexcel.views.send_log', ['Steven_X_Xu@wistron.com','Vicily_Wei@wistron.com'], {}, '>> /var/run.log'),
    ('0 4 * * *','app.DBexcel.views.crontab_test','>> /var/run.log'),
    ('0 8 * * *','app.index.views.ti_xing','>> /var/run.log'),
    ('0 8 * * *','app.index.views.applyTiXing','>> /var/run.log'),
    ('0 12 * * *','app.index.views.ti_xing','>> /var/run.log'),
    ('0 16 * * *','app.index.views.ti_xing','>> /var/run.log'),
    # ('*/20 * * * *','app.NGrate.views.check_NGRate','>> /var/run.log'), #设定NG率的监控的定时任务去做监控数据
    # ('*/20 * * * *','app.maintain_monitor.views.Check_monitor_equipment','>> /var/run.log'), #设定设备保养监控的函数的定时的任务去做监控的数据
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
TEMPLATE_DIRS = (os.path.join(BASE_DIR,'templates'),)
STATIC_ROOT = os.path.join(BASE_DIR,'static')
# STATICFILES_DIRS=(
# os.path.join(BASE_DIR, 'static/'),
# )
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
#存放生成预算表单的报表的文件的目录
MEDIA_CHANGE_URL ='/report/'
MEDIA_CHANGE_ROOT = os.path.join(BASE_DIR,'report')
#存放生成报表的文件的目录
MEDIA_MONITOR_URL ='/monitor/'
MEDIA_MONITOR_ROOT = os.path.join(BASE_DIR,'monitor')
#存放设备保养监控文件的目录
MEDIA_MAINTAIN_MONITOR_URL ='/maintainor/'
MEDIA_MAINTAIN_MONITOR_ROOT = os.path.join(BASE_DIR,'maintainor')
#存放设备添加的目录
MEDIA_ADD_URL ='/maintain/'
MEDIA_ADD_ROOT = os.path.join(BASE_DIR,'maintain')

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

